### ISSUE TITLE
tv2.dk

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/listear#1]
Article videos are broken due to `_adunit_` in Liste AR. This was first brought to my attention in 
* https://github.com/AdguardTeam/AdguardFilters/issues/75894

Example page: 
* `https://sport.tv2.dk/skisport/2021-02-26-tvillingesoester-kostede-plads-i-vm-finale-hun-er-lidt-af-en-idiot`

Adblockers: uBO 1.33.3b8 + I Don't Care About Cookies 3.2.7
Browser: Chrome 88.0.4324.190 x64
OS: Windows 10 20H2

Lists: 
* https://user-images.githubusercontent.com/22780683/109295193-96470e80-782e-11eb-89f5-388b3655fe78.png

Page screensot: 
* https://user-images.githubusercontent.com/22780683/109295216-9fd07680-782e-11eb-9d8c-9971526cdd32.png

The black box error means: "Oops, something went wrong. An error sadly occured during playback. Try to reload the page."

**Comment by smed79** [comment]
Fixed https://github.com/easylist/listear/commit/7a32e4e35147d19530d908a32b54133fd13233e3

Thank you.
