### ISSUE TITLE
digiato.com 

### ISSUE THREAD

**Issue by edivaniadc** [easylist/listear#15]
### URLs:
`https://digiato.com/`
`https://digiato.com/article/2022/02/02/omicron-ba-2-not-more-severe-than-ba-1`

### Issue:
Animated ads throughout the main page and also on supgages (at the top).

### Screenshot:
https://user-images.githubusercontent.com/57706597/152611033-f00f328c-e762-4dad-860e-d55a64038291.png

https://user-images.githubusercontent.com/57706597/152612859-dbd8b295-d883-4dfb-a53b-0756ebdfe315.png"

### Suggested filter:
`||click.digiato.com/media/$media,domain=digiato.com` - for the main page
`||display.netbina.com/banner^$subdocument,domain=digiato.com` - for subpages

**Comment by smed79** [comment]
Persian language (Iranian) **not** Arabic.

**Comment by edivaniadc** [comment]
> Persian language (Iranian) **not** Arabic.

Hi @smed79 thanks for pointing that out. I was actually not aware of the existence of AdBlock Farsi list, so I'm sorry for creating the issue in the wrong list. 
Thanks also for creating [PR24](https://github.com/SlashArash/adblockfa/pull/24/files)

**Comment by smed79** [comment]
> I was actually not aware of the existence of AdBlock Farsi list

Known Adblock Plus subscriptions are listed at 
https://adblockplus.org/subscriptions
https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html
https://fanboy.co.nz/filters.html
