### ISSUE TITLE
akhbarelyom.com

### ISSUE THREAD

**Issue by SonicPlushBros** [easylist/listear#2]
`https://akhbarelyom.com/`

There are a few blank spots on the page for ads, and also a floating banner image that you can close.

This is a example of what I mean:

[https://user-images.githubusercontent.com/89158249/129951807-1a1cd1c7-706f-45e3-836c-1898f6b13960.png](https://user-images.githubusercontent.com/89158249/129951807-1a1cd1c7-706f-45e3-836c-1898f6b13960.png)

**Comment by smed79** [comment]
> There are a few blank spots on the page for ads

Subscribe to **Liste FR** from https://adblockplus.org/subscriptions and test again.
For more info see >> https://github.com/easylist/listear/issues/5#issuecomment-924841349

https://github.com/easylist/listear/blob/1541882a4fc444eee4e193c4115c80e559025f64/Liste_AR.txt#L6

> also a floating banner image

The floating image is not an ad.

To block **in-page pop-ups** which is an annoyance, subscribe to **Fanboy's Annoyance List** from
- https://easylist.to/ or https://secure.fanboy.co.nz/
