### ISSUE TITLE
lodynet.win

### ISSUE THREAD

**Issue by eporubin** [easylist/listear#28]
Hi, could you please ad this specific hide filter for this website `lodynet.win##aside` to hide this add on the page: 
![image](https://user-images.githubusercontent.com/33602691/219634271-d96a23ca-4adb-4621-9bfa-4840657f5224.png)
Thank you

**Comment by smed79** [comment]
Hi, 

seems to be self-promotion for their android app.

I submit a PR to the annoyance list https://github.com/easylist/easylist/pull/15041
