### ISSUE TITLE
skynewsarabia.com

### ISSUE THREAD

**Issue by tadtk** [easylist/listear#29]
Excuse me, SkynewsArabia breaking News bar the is intrusive & distractive and it always pops up whenever `skynewsarabia.com` website is opened either on mobile phone or desktop with no way to dismiss or close it & I manged to block it on my desktop by adding this blocking rule to My filters `skynewsarabia.com##.breaking-news-ticker` but I can't do so on my mobile phone on the Adguard app that uses **ListeAR** so I hope that you can add it to the default blocking rules of **ListeAR**. 

screenshot:
- https://user-images.githubusercontent.com/126111369/220821988-672dc156-3c3e-4498-a6e9-2f5c17f0a944.png

**Comment by smed79** [comment]
Hello, 
unfortunately,  as it is not advertising it will not be added to the main list.

add the below filter
```
||skynewsarabia.com/asset/*/breakingNews.html
```

**Comment by smed79** [comment]
It is more an **annoyance**, so i will submit a filter to the more appropriate list **Fanboy's Annoyance List**.
