### ISSUE TITLE
egybest.media

### ISSUE THREAD

**Issue by ghajini** [easylist/listear#34]
**URL=** `https://egybest.media/series/انمي-jujutsu-kaisen-tv/season/2/episode/20`
chrome stable, ublock stable
 **issue description** = there are some fake buttons unblocked which are 
![image](https://github.com/easylist/listear/assets/20338483/e0bfe99c-5a5a-4dfe-9dde-2f9a04c2c148)

can you fix this regional AR list ,having fixed in regional list is preferrable

**Comment by smed79** [comment]
These links are already [hidden](https://github.com/easylist/listefr/blob/e1bfe7bc10dbf0b24e7d302ff262ce31c1ecd60a/liste_fr.txt#L16813) in **Liste FR**.

Also take note that **Liste AR** is supplement for [EasyList / Liste FR](https://github.com/easylist/listefr) (_shouldn't be used alone_).

[![ABP subscriptions](https://github.com/easylist/listear/assets/1873139/e38165a5-b225-41d7-a5ea-7a257664531a)](https://adblockplus.org/en/subscriptions?)
