### ISSUE TITLE
Custom DNS blocklists/hosts file?

### ISSUE THREAD

**Issue by bigplayer-ai** [easylist/listear#35]
Hey,
is there any Adguard DNS blocklists/hosts file?

**Comment by smed79** [comment]
Hello, 

Liste AR (only) https://raw.githubusercontent.com/easylist/listear/master/hosts.txt
Liste FR (only) https://raw.githubusercontent.com/easylist/listefr/master/hosts.txt

If you are interested i maintain an unified [EasyList hosts](https://github.com/smed79/easylist-hosts?tab=readme-ov-file#easylist-hosts) file which include all filter lists.
