### ISSUE TITLE
[NSFW] alarbda.com

### ISSUE THREAD

**Issue by Yuki2718** [easylist/listear#37]
Unblocked AdSpyglass adserver `arabs.alarbda.com`

**Comment by smed79** [comment]
I am enable to reproduce.

**Comment by Yuki2718** [comment]
> I am enable to reproduce.

Hmmm..

<details>
<summary>Screenshot</summary>

![alarbda](https://github.com/user-attachments/assets/30fb607b-cd5c-45c4-89d1-e505bd18535b)

</details>
