### ISSUE TITLE
meyadin.net

### ISSUE THREAD

**Issue by MasterKia** [easylist/listear#38]
`https://meyadin.net/node/28339`

Drupal anti-copy/right-click script:
```adb
||meyadin.net/sites/default/files/js/js_pd0FglZaH7laLogzU32VpTt4HY0cW9blseRaXX5P0aw.js
```

Also when you try to save images, it replaces them with an empty gif.

**Comment by smed79** [comment]
Hey,

thank you for reporting, but as you mentioned, the Arabic list does not support these kinds of annoyances.

Should be reported at [EasyList repo](https://github.com/easylist/easylist/issues) to be added to [Fanboy's Annoyance List](https://easylist.to/easylist/fanboy-annoyance.txt).

@ryanbr fyi.
