### ISSUE TITLE
alnaharegypt.com

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/listear#4]
### URL(s) where the issue occurs

`alnaharegypt.com`

### Describe the issue

Ads on sides.

### Screenshot(s)

With ads:
[https://user-images.githubusercontent.com/52135169/133895604-abe5f35f-587f-4777-8c36-3c226aee2ebf.png](https://user-images.githubusercontent.com/52135169/133895604-abe5f35f-587f-4777-8c36-3c226aee2ebf.png)

Without ads:
[https://user-images.githubusercontent.com/52135169/133895836-9d12af45-6c9a-4438-be42-e8e46119107b.png](https://user-images.githubusercontent.com/52135169/133895836-9d12af45-6c9a-4438-be42-e8e46119107b.png)

### Adblocker

uBlock Origin version1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`||alnaharegypt.com/bnr/`

**Comment by smed79** [comment]
See https://github.com/easylist/listear/issues/5#issuecomment-924841349
