### ISSUE TITLE
elamwal.com

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/listear#5]
### URL(s) where the issue occurs

`https://www.elamwal.com`

### Describe the issue

Several ads (in the form of photos) around the page's top.

### Screenshot(s)
With ads:

[https://user-images.githubusercontent.com/52135169/133895722-324dbdc5-8f90-4879-a181-ccfdfdd6f518.png](https://user-images.githubusercontent.com/52135169/133895722-324dbdc5-8f90-4879-a181-ccfdfdd6f518.png)

Without ads:

[https://user-images.githubusercontent.com/52135169/133895722-324dbdc5-8f90-4879-a181-ccfdfdd6f518.png](https://user-images.githubusercontent.com/52135169/133895794-a0246f98-1066-474f-88e2-ca7adab9a43e.png)

### Adblocker 

uBlock Origin version 1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`||elamwal.com/bnr/`

**Comment by smed79** [comment]
ads are already blocked by the filter `.com/bnr/` found in **Liste FR** 

https://github.com/easylist/listefr/blob/dfd4e3581ea6f5b023b7dceac2b196ea86fe095e/liste_fr.txt#L331

FYI, [**Liste AR**](https://easylist-downloads.adblockplus.org/Liste_AR.txt) is supplement subscription or **EasyList**+**Liste_FR** so It is recommended to use it together with **Liste FR**

https://github.com/easylist/listear/blob/1541882a4fc444eee4e193c4115c80e559025f64/Liste_AR.txt#L6
see: 
- https://easylist.to/2013/02/17/liste-ar-is-now-an-affiliated-subscription.html

ref : 
- https://issues.adblockplus.org/ticket/4890/ (@ThomasGreiner @wizmak)
- https://git.io/vpQK1
