### ISSUE TITLE
bank-zone.com

### ISSUE THREAD

**Issue by Mennaruuk** [easylist/listear#6]
### URL(s) where the issue occurs

`https://bank-zone.com`

### Describe the issue

Ad on top left.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/133896184-4f8c5cd3-74e7-41c0-b153-d313f4924c71.png)

### uBlock Origin version

1.37.2

### Browser name and version

Firefox 92.0

### Settings

N/A

### Notes

I propose:

`bank-zone.com##.stream-item-top`

**Comment by smed79** [comment]
1st ad banner is already blocked `-728-x-90.` found in **Liste FR** (see https://github.com/easylist/listear/issues/5#issuecomment-924841349)

2nd ad banner, added
